### ISSUE TITLE
Decide Project Goal - App use

### ISSUE THREAD

**Issue by pablowbk** [chingu-voyages/v8-geckos-team-06#3]
Define what will the final project / App should do.
What is the value the user gets.

**Comment by pablowbk** [comment]
@sammartfrank @zentech 
Let's post here our *thoughts / ideas / problems that need solution*
If we can come up we **3 each**, that should help us kick this thing started!

**Comment by pablowbk** [comment]
## Pablo's input:

- [ ] An app for **junior devs** , that **finds open source projects** they can contribute to, in order to gain experience in **collaborating**. (GitHub API ?)

- [x] An app for a **Startup/NGO** that helps them **get subscribers**, showcasing their info in an **engaging way** (D3 ?)

- [ ] An app for **podcast lovers**, that suggests podcasts **based on user input** (favorite topics / categories), with maybe a gallery of favorites? **spotify clone**?

- [ ] an App for **developers / freelancers** that serves as a **CV wizard**, with at **pdf as result**, with email / linkedin integration if possible? Must have great ui/ux simple yet powerful

**Comment by sammartfrank** [comment]
#Franks Input
---
 _**I think the App should try to meet our three levels of expertise and experience.**_.

- [ ] An App designed to help the user Find out theyr good and bad habits.  And the time they kick in in the day. That way it can provide usefull data for possible harming cicles.

- [ ] An App to locate possible overdue expired Medicines to the person in need. From Oncology to a painkiller.  That way tthose meds dont go to waste.

- [ ] An App that provides a usefull o uplifting quote when the user is passing throu rought times. Even a Joke or something quick that could cheer him/her up.

**Comment by zentech** [comment]
hey guys both ideas sound great.... the medical app I'm intrigued. I think a lot more people can benefit from something like this.. I'm trying to figure out if we would need a database for the user to enter the info.. and maybe provide some rest api so other user can benefit

**Comment by zentech** [comment]
### #George Input Zentech
### Yoga app
I was thinking on creating a yoga app.. which user can enter their location and they would get the location of the closest yoga gym / schools. Also the app would have other features like yoga exercises, for beginners, advance etc.. as well as guided meditation. I don't know if this is a bit ambitious for what we're want to do... it is just my input... yoga has lots of following and I think many people would like it and use it.. let me know what you think. so I can provide a more concrete proposal

- [ ] retrieve a list of nearby Yoga schools

- [ ] users can log in and get notification of classes and offers by these schools

- [ ] users can follow yoga sequence depending on beginning or advance level

- [ ] forum where users can discuss yoga topics

- [ ] provide rest api so mobile apps can use the service

- [ ] keep track of calories lost for every user while following a yoga session

**Comment by pablowbk** [comment]
MedHUB is born! Web app that helps people dispose of non-expired meds so that others on the same treatment may use them, thus reducing waste and saving people money
