### ISSUE TITLE
[Sprint Zero] Project MockUp

### ISSUE THREAD

**Issue by pablowbk** [chingu-voyages/v8-geckos-team-06#6]
layout a mockup of the project using any medium avaialble

**Comment by sammartfrank** [comment]
So we need to start the layout of our App. What you guys feel that could look sharp and modern?.

I like fullpage components that scroll on click to further fullpage components in case of Tablet and Desktops.

And minimalistic on Mobile.

**Comment by pablowbk** [comment]
App diagrams

MVP:
https://www.draw.io/#G1C3f5_LqnOkXOBWC0Fz7e2hQwnAmDxh9S

UX Flow:
https://drive.google.com/file/d/1BbkG1rU6z56KQsRb9xEJnrev6p7wCUEv/view?usp=sharing

**Comment by pablowbk** [comment]
![Captura de pantalla de 2019-04-04 11-48-51](https://user-images.githubusercontent.com/36734796/55572764-b7ecf900-56de-11e9-8cde-74c185ef55b6.png)

**Comment by pablowbk** [comment]
![image (1)](https://user-images.githubusercontent.com/36734796/55572783-c63b1500-56de-11e9-85ce-23797940778b.png)

**Comment by pablowbk** [comment]
![image (2)](https://user-images.githubusercontent.com/36734796/55572801-d5ba5e00-56de-11e9-9b78-e55c7b18ff85.png)
![image](https://user-images.githubusercontent.com/36734796/55572803-d5ba5e00-56de-11e9-89fb-283a569bf032.png)

**Comment by zentech** [comment]
I like it... I think full page is good option.
