### ISSUE TITLE
[Git] Decide on a git stategy

### ISSUE THREAD

**Issue by pablowbk** [chingu-voyages/v8-geckos-team-06#7]
Will the team fork the repo or work with dev branch?

**Comment by zentech** [comment]
how teams of developers usually work

**Comment by pablowbk** [comment]
With Franco, yesterday, we chose to go with a Dev branch, and clone the repo locally.

**Comment by zentech** [comment]
ok.. so I have to create my own fork of dev branch... what are we building?

**Comment by pablowbk** [comment]
clone the repo locally and branch off the dev branch

**Comment by pablowbk** [comment]
it's kinda akward to communicate like this, any chance we can use a more fluid channel?

**Comment by zentech** [comment]
yes.. sure

**Comment by zentech** [comment]
I'm on slack right now

**Comment by pablowbk** [comment]
Team decided to work on Dev branch
